/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WithdrawalLimit = IDL.Record({
  'lastResetTimestamp' : IDL.Int,
  'todayWithdrawn' : IDL.Nat,
  'limitPerTransaction' : IDL.Nat,
  'limitPerDay' : IDL.Nat,
});
export const UserAccount = IDL.Record({
  'notificationPreferences' : IDL.Record({
    'coinChime' : IDL.Bool,
    'alertStyle' : IDL.Variant({ 'top' : IDL.Null, 'center' : IDL.Null }),
  }),
  'twoFactorEnabled' : IDL.Bool,
  'owner' : IDL.Principal,
  'type' : IDL.Variant({
    'personal' : IDL.Null,
    'business' : IDL.Null,
    'royal' : IDL.Null,
  }),
  'displayPreferences' : IDL.Record({
    'frameSize' : IDL.Nat,
    'darkIntensity' : IDL.Nat,
    'immersive' : IDL.Bool,
  }),
  'withdrawalLimit' : WithdrawalLimit,
});
export const UserProfile = IDL.Record({
  'nickname' : IDL.Text,
  'linkedAccounts' : IDL.Vec(IDL.Text),
  'accountType' : IDL.Variant({
    'personal' : IDL.Null,
    'business' : IDL.Null,
    'royal' : IDL.Null,
  }),
  'avatarConfig' : IDL.Record({
    'color' : IDL.Text,
    'crown' : IDL.Text,
    'clothes' : IDL.Text,
  }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccount' : IDL.Func([IDL.Principal], [IDL.Opt(UserAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawalLimit' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WithdrawalLimit)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAccounts' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
  'saveAccount' : IDL.Func([UserAccount], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WithdrawalLimit = IDL.Record({
    'lastResetTimestamp' : IDL.Int,
    'todayWithdrawn' : IDL.Nat,
    'limitPerTransaction' : IDL.Nat,
    'limitPerDay' : IDL.Nat,
  });
  const UserAccount = IDL.Record({
    'notificationPreferences' : IDL.Record({
      'coinChime' : IDL.Bool,
      'alertStyle' : IDL.Variant({ 'top' : IDL.Null, 'center' : IDL.Null }),
    }),
    'twoFactorEnabled' : IDL.Bool,
    'owner' : IDL.Principal,
    'type' : IDL.Variant({
      'personal' : IDL.Null,
      'business' : IDL.Null,
      'royal' : IDL.Null,
    }),
    'displayPreferences' : IDL.Record({
      'frameSize' : IDL.Nat,
      'darkIntensity' : IDL.Nat,
      'immersive' : IDL.Bool,
    }),
    'withdrawalLimit' : WithdrawalLimit,
  });
  const UserProfile = IDL.Record({
    'nickname' : IDL.Text,
    'linkedAccounts' : IDL.Vec(IDL.Text),
    'accountType' : IDL.Variant({
      'personal' : IDL.Null,
      'business' : IDL.Null,
      'royal' : IDL.Null,
    }),
    'avatarConfig' : IDL.Record({
      'color' : IDL.Text,
      'crown' : IDL.Text,
      'clothes' : IDL.Text,
    }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccount' : IDL.Func([IDL.Principal], [IDL.Opt(UserAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawalLimit' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WithdrawalLimit)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAccounts' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
    'saveAccount' : IDL.Func([UserAccount], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };